services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
    volumes:
      - ${VOLUME_ROOT}/duplicati/config:/config
      - ${VOLUME_ROOT}/duplicati/source:/source
      - ${VOLUME_ROOT}:/source/configs
      - ${STORAGE_ROOT}/backups:/backups
      - /var/backups/homelab:/backups-sd
    ports:
      - 8200:8200
    restart: unless-stopped
    networks:
      - homelab-network